zendesk_url = "https://getchef.zendesk.com/api/v2"
zendesk_user = "username_email@chef.io"
zendesk_token = "GetThisFromLastPass"
logfile = "~/.support/ticket.log"
# Auto download ticket attachments when opening a ticket
autodownload = false
open_broswer = false
ticket_path = "~/support/.ticket"
# Sendsafely configuration
sendsafely_url = "https://secure.chef.io/"
sendsafely_key_id = "Obtain from API Keys section under https://secure.chef.io/secure/profile/"
sendsafely_key_secret = "Obtain from API Keys section under https://secure.chef.io/secure/profile/"
