#!/usr/bin/env ruby
# encoding: utf-8
# Usage: ticket delete
# Summary: Delete local info for given ticket id
# Provide ticket completions
# Built-in help

$LOAD_PATH.unshift File.join(ENV['_TICKET_ROOT'], 'share/ticket')

require 'clamp'
require 'colorize'
require 'highline'
require 'fileutils'
require 'helpers/ticket'
require 'helpers/ticket_info'

class DeleteCommand < Ticket::Command
  include TicketInfo

  attr_accessor :ticket

  option '--complete', :flag, 'autocomplete output', hidden: true
  option ['-y', '--yes'], :flag, 'Confirm all questions with yes'

  parameter '[TICKET_ID]', 'ticket_id', :attribute_name => :ticket_id

  def execute
    return autocomplete if complete?

    if ticket_id.nil?
      signal_usage_error "Please specify a ticket_id to delete"
    end

    ticket = Ticket::Info.load(ticket_id)
    ticket.delete
  rescue Ticket::NotFound => e
    puts e.message.red
  end

  def autocomplete
    opts = all_ticket_ids

    puts opts.join("\n")
    exit
  end
end

DeleteCommand.run
