#!/usr/bin/env ruby
# encoding: utf-8
# Usage: ticket peek
# Summary: Describe peek command here
# Provide ticket completions

$LOAD_PATH.unshift File.join(ENV['_TICKET_ROOT'], 'share/ticket')

require 'clamp'
require 'helpers/ticket_info'

class PeekCommand < Clamp::Command
  include TicketInfo

  option '--complete', :flag, 'autocomplete output', hidden: true
  parameter '[TICKET_ID]', 'ticket_id', :attribute_name => :ticket_id

  def execute
    return autocomplete if complete?

    exec "ticket open --no-shell #{ticket_id}"
  end

  def autocomplete
    opts = all_ticket_ids

    puts opts.join("\n")
    exit
  end
end

PeekCommand.run
