#!/usr/bin/env ruby
# encoding: utf-8
# Usage: ticket list
# Summary: List clients or tickets for clients if client is given
# Provide ticket completions
# Built-in help

$LOAD_PATH.unshift File.join(ENV['_TICKET_ROOT'], 'share/ticket')

require 'clamp'
require 'colorize'
require 'helpers/ticket_info'

class ListCommand < Clamp::Command
  include TicketInfo

  option '--complete', :flag, 'autocomplete output', hidden: true
  option '--ids', :flag, 'list just ticket ids'
  option ['-q', '--quiet'], :flag, 'less verbose output'

  parameter '[CLIENT]', 'client name', :attribute_name => :client

  def execute
    return autocomplete if complete?

    if ids?
      puts "Listing all ticket ids".green unless quiet?
      puts all_ticket_ids.join("\n")
    elsif client
      puts "Listing known client names".green unless quiet?
      puts ticket_ids(client).join("\n")
    else
      puts "Listing known client names".green unless quiet?
      puts client_list.join("\n")
    end

    # example usage
    # unless File.exists?(file)
    #   signal_usage_error "file doesn't exist"
    # end

    # Put the rest of the list command here
  end

  def autocomplete
    puts client_list.join("\n")
    exit
  end
end

ListCommand.run
