#!/usr/bin/env ruby
# frozen_string_literal: true

# Usage: ticket peek
# Summary: Open browser window for to zendesk ticket
# Provide ticket completions
# Built-in help

$LOAD_PATH.unshift File.join(ENV["_TICKET_ROOT"], "share/ticket")

require "clamp"
require "helpers/ticket_info"

class PeekCommand < Clamp::Command
  include TicketInfo

  option "--complete", :flag, "autocomplete output", hidden: true
  parameter "[TICKET_ID]", "ticket_id", attribute_name: :ticket_id

  def execute
    return autocomplete if complete?

    exec "open #{ticket_url}"
  end

  def ticket_url
    "https://getchef.zendesk.com/agent/tickets/#{ticket_id}"
  end

  def autocomplete
    opts = all_ticket_ids

    puts opts.join("\n")
    exit
  end
end

PeekCommand.run
