#!/usr/bin/env ruby
# frozen_string_literal: true

# Usage: ticket list
# Summary: List clients or tickets for clients if client is given
# Provide ticket completions
# Built-in help

$LOAD_PATH.unshift File.join(ENV['_TICKET_ROOT'], 'share/ticket')

require 'clamp'
require 'colorize'
require 'helpers/ticket'

class ListCommand < Ticket::Command
  option '--complete', :flag, 'autocomplete output', hidden: true
  option '--ids', :flag, 'list just ticket ids'
  option ['-q', '--quiet'], :flag, 'less verbose output'

  parameter '[CLIENT]', 'client name', attribute_name: :client

  def execute
    return autocomplete if complete?

    if ids?
      puts 'Listing all ticket ids'.green unless quiet?
      puts Ticket::Info.ids.sort.join("\n")
    elsif client
      puts "Listing ticket numbers for #{client}".green unless quiet?
      puts Ticket::Info.ids(client).sort.join("\n")
    else
      puts 'Listing client'.green unless quiet?
      puts Ticket::Info.clients.map(&:capitalize).sort.join("\n")
    end
  end

  def autocomplete
    puts Ticket::Info.clients.sort.join("\n")
    exit
  end
end

ListCommand.run
