#!/usr/bin/env ruby
# encoding: utf-8
# Usage: ticket download TICKET_ID
# Summary: Downloads all attachments from a ticket
# Provide ticket completions
# Built-in help

$LOAD_PATH.unshift File.join(ENV['_TICKET_ROOT'], 'share/ticket')

require 'clamp'
require 'helpers/ticket_info'
require 'helpers/actions'
require 'colorize'

Clamp.allow_options_after_parameters = true
class DownloadCommand < Clamp::Command
  include TicketInfo

  option '--complete', :flag, 'autocomplete output', hidden: true
  option '--verbose', :flag, 'verbose output'
  option '--force', :flag, 'force redownload of files'

  parameter '[TICKET_ID]', 'ticket_id', attribute_name: :ticket_id

  def execute
    return autocomplete if complete?

    # dup ticket_id cause wierd things happen from clamp when updating arg params
    # on our own
    id = ticket_id.dup

    unless find_local_ticket_info.nil?
      ticket_info = load_ticket({ file: find_local_ticket_info })

      if !id.nil? && ticket_info['id'] != id
        signal_usage_error <<~EOH
        The specified ticket id does not match the one for the current directory,
               either remove the current ticket id from the command or switch to
               another directory.
        EOH
      end

      id = ticket_info['id']
    end

    if id.nil?
      signal_usage_error "Unable find a ticket to download files from (id: #{id.inspect})".red
    end

    Ticket::Actions.download(id, verbose: verbose?, force: force?)
  end

  def autocomplete
    opts = %w{ --help }

    puts opts.join("\n")
    exit
  end
end

DownloadCommand.run
