#!/usr/bin/env ruby
# frozen_string_literal: true

# Usage: ticket combine-files
# Summary: Tries to detect split ticket files and recombines them
# Provide ticket completions
# Built-in help

$LOAD_PATH.unshift File.join(ENV["_TICKET_ROOT"], "share/ticket")

require "clamp"
require "helpers/common"
require "helpers/ticket"

class CombineCommand < Clamp::Command
  include CommonHelpers

  option "--complete", :flag, "autocomplete output", hidden: true
  option ["-y", "--yes"], :flag, "Answer yes to all questions", default: false

  parameter "[SPLIT_FILES] ...", "files to combine", attribute_name: :input_files

  def execute
    return autocomplete if complete?

    Ticket::Actions.combine_files(input_files, force: yes?)
  end

  def autocomplete
    opts = []
    opts += Dir.glob("*.part*")
    opts += %w[--help -y]

    puts opts.join("\n")
    exit
  end
end

CombineCommand.run
